### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Application' not found in /usr/local/var/www/fend/vendor/fend/fend/src/Console/Command.php:25

### ISSUE THREAD

**Issue by 7small7** [tal-tech/fend#2]
```shell
var/www/fend via 🐘 v7.1.32
❯ php ./bin/fend Swoole -c app/Config/Swoole.php start


PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Application' not found in /usr/local/var/www/fend/vendor/fend/fend/src/Console/Command.php:25
Stack trace:
#0 /usr/local/var/www/fend/bin/fend(11): Fend\Console\Command->__construct()
#1 {main}
  thrown in /usr/local/var/www/fend/vendor/fend/fend/src/Console/Command.php on line 25
```
框架安装按照文档默认安装，采用Swoole模式 Nginx代理配置。提示上述错误信息。

**Comment by 137-rick** [comment]
这个组件是可选组件，可以通过composer require symfony/console:^5.1 安装
swoole启动有两个方式，你用的正好是用这个组件的方式，可以选用bin/start.php启动，这个无需此组件
这么设计的原因是symfony console即使不使用也会有大量文件加载，小伙伴比较排斥这个所以默认没有集成

**Comment by yozman** [comment]
@archdesigner 

关于框架的使用模式透出，感觉应该有两个对应的 preset(skeleton)，分别为 preset-swoole 和 preset-fpm

大量不必要的文件加载，感觉可以借鉴一下 js 社区 webpack 的 treeshaking 方案，通过编译的方式保证线上 release 的代码没有多余没用到的文件加载

---

还有 bin/start.php 这种感觉也应该维护成一个 composer package 然后在 preset 的 composer.json 里通过

```json
...
"require": {
  ...
  "fend/cli": "1.0.0"
  ...
},
"scripts": {
  "app": "fend-cli"
},
...
```

的形式定义，并通过 `composer app -- xxx` 来使用
