### ISSUE TITLE
大佬们， Client 和 ClientBuilder 这二个类方便添加下吗？

### ISSUE THREAD

**Issue by coding-lover** [tal-tech/fend#8]
![image](https://user-images.githubusercontent.com/9207532/94140075-4b028b80-fe9d-11ea-9aee-6d6fac482330.png)

**Comment by 137-rick** [comment]
emm没看懂你要什么具体功能，不过通用的话可以直接提pr

**Comment by coding-lover** [comment]
这里少了 client 和 clientBuilder 这二个类，这二个类应该是对接了 es6 创建索引 字段之类的接口； 如果你们方便就push下，懒得再去造轮子了

**Comment by 137-rick** [comment]
我去看看～

**Comment by 137-rick** [comment]
你好，要不直接来个pr吧，我没领悟到你的意思，捂脸

**Comment by coding-lover** [comment]
这个意思 ~~
{
    "x_name":"request.info",
    "x_version":"fend-1.2",
    "x_trace_id":"MacBook-Pro-3.local_3934_117983876.06787_199",
    "x_rpc_id":"1.1",
    "x_department":"tal_wx",
    "x_server_ip":"MacBook-Pro-3.local",
    "x_timestamp":1601183876,
    "x_duration":"0.0075",
    "x_pid":"3934",
    "x_module":"php_request_end",
    "x_client_ip":"0.0.0.0",
    "x_action":"local.fend.com/elastic/create",
    "x_param":"{"post":[],"get":{"s":"\/elastic\/create","_":"1601183812893"},"body":""}",
    "x_source":"http://local.fend.com/index/elastic",
    "x_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "x_code":"500",
    "x_backtrace":"Class 'Elasticsearch\ClientBuilder' not found
#0 /data/www/fend_test/vendor/fend/fend/src/ElasticSearch/ElasticSearch6.php(43): Fend\ElasticSearch\ElasticSearch6->__construct('default')
#1 /data/www/fend_test/app/Http/Elastic.php(34): Fend\ElasticSearch\ElasticSearch6::Factory('default')
#2 /data/www/fend_test/vendor/fend/fend/src/Router/Router.php(74): App\Http\Elastic->create()
#3 /data/www/fend_test/vendor/fend/fend/src/Router/Middleware/HttpRequestHandler.php(52): Fend\Router\Router->process(Object(Fend\Request), Object(Fend\Router\Middleware\HttpRequestHandler))
#4 /data/www/fend_test/vendor/fend/fend/src/Router/Router.php(39): Fend\Router\Middleware\HttpRequestHandler->handle(Object(Fend\Request))
#5 /data/www/fend_test/vendor/fend/fend/src/Router/DefaultRouter.php(76): Fend\Router\Router->invokeFunc('\\App\\Http\\Elast...', 'create', Array)
#6 /data/www/fend_test/vendor/fend/fend/src/Router/Dispatcher.php(59): Fend\Router\DefaultRouter->dispatch('local.fend.com', 'GET', Array)
#7 /data/www/fend_test/www/index.php(90): Fend\Router\Dispatcher->dispatch('local.fend.com', 'GET', '/elastic/create')
#8 {main}",
    "x_response":"",
    "x_response_length":0,
    "x_extra":"{"unknow":[]}"
}

**Comment by 137-rick** [comment]
国庆期间我会处理下这个

**Comment by coding-lover** [comment]
原来是少了 elasticsearch 的sdk  😅

**Comment by 137-rick** [comment]
(((o(*ﾟ▽ﾟ*)o)))
